#!/usr/bin/env bash

# Git
alias g="git"
alias gs="git status"
alias gw="git show"
alias gw^="git show HEAD^"
alias gw^^="git show HEAD^^"
alias gw^^^="git show HEAD^^^"
alias gw^^^^="git show HEAD^^^^"
alias gd="git diff HEAD"  # What's changed? Both staged and unstaged.
alias gdo="git diff --cached"  # What's changed? Only staged (added) changes.
# for gco ("git commit only") and gca ("git commit all"), see functions.sh.
# for gget (git clone and cd), see functions.sh.
alias gcaf="git add --all && gcof"
alias gcof="git commit --no-verify -m"
alias gcac="gca Cleanup."
alias gcoc="gco Cleanup."
alias gcaw="gca Whitespace."
alias gcow="gco Whitespace."
alias gpp='git pull --rebase && git push'
alias gppp="git push -u"  # Can't pull because you forgot to track? Run this.
alias gps='(git stash --include-untracked | grep -v "No local changes to save") && gpp && git stash pop || echo "Fail!"'
alias go="git checkout"
alias gb="git checkout -b"
alias got="git checkout -"
alias gom="git checkout master"
alias grb="git rebase -i origin/master"
alias gr="git branch -d"
alias grr="git branch -D"
alias gcp="git cherry-pick"
alias gcpp="git cherry-pick -"  # "cherry-pick previous", e.g. the head of the branch we just left
alias gam="git commit --amend"
alias gamm="git add --all && git commit --amend -C HEAD"
alias gammf="gamm --no-verify"
alias gba="git rebase --abort"
alias gbc="git add -A && git rebase --continue"
alias gbm="git fetch origin master && git rebase origin/master"


# when i say git i mean hub
#eval "$(hub alias -s)"

alias g="git"

# ---------- ADD ----------
alias ga="git add"
alias ga.="git add ."

# ---------- PUSH ----------
alias gp='git push'
alias gpo="git push origin"
alias gpfo="git push -f origin"
alias gpom="git push origin master"
alias gpfom="git push -f origin master"
alias gpao="git push --all origin"
alias gpfao="git push -f --all origin"
alias gpd="git push --delete"
alias gpod="git push origin --delete"

# ---------- PULL ----------
alias gpl='git pull'
alias gpla='git pull --all'
alias gplo='git pull origin'
alias gplr='git pull --rebase'
alias gplro='git pull --rebase origin'


# ---------- FETCH ----------
alias gf='git fetch'
alias gfa='git fetch --all'
alias gfo='git fetch origin'

# ---------- BRANCH ----------
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -d"
alias gbD="git branch -D"
alias gub="git remote update origin --prune && echo '\nNew Branch List:\n' &&git branch --all"

# ---------- STATUS ----------
alias gs='git status -sb'

# ---------- COMMIT ----------
alias gc='git commit --cleanup=scissors -m'
# don't validate commit

alias gca='git commit --cleanup=scissors --amend'
alias gcan='git commit --cleanup=scissors --amend -n'

# ---------- DIFF ----------
alias gd='git diff'

# ---------- CHECKOUT ----------
alias gco='git checkout'
alias gcob='git checkout -b'

# ---------- REBASE ----------
alias grb='git rebase'
alias grbi='git rebase --interactive'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'

# ---------- MERGE ----------
alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gms='git merge --squash'

# ---------- LOG ----------
alias glog='git log --graph -n 30'
# alias gl='git log --pretty=oneline -n 20 --graph --abbrev-commit'
alias gl='git log --graph -n 30'
# show me all commits
alias gla='git log --graph'
# show me details
alias gld="git log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative"

# ---------- REMOTE ----------
alias grv='git remote -v'
# git update remote
alias gurl='git remote set-url origin'

# ---------- RESET ----------
alias gr='git reset'
alias gr.='git reset .'
# throw away changes since commit
alias grh='git reset --hard'
# throw away changes since commit on <path>
alias grf='git checkout HEAD --'

# ---------- CHERRY PICK ----------
alias gcp='git cherry-pick'
alias gcpc='git cherry-pick -- continue'
alias gcpa='git cherry-pick --abort'

# ---------- BROWSE ----------
alias gbr='git browse'

# Git aliases
# More Git tips http://firstaidgit.io/
alias gss="git status -s"
alias gp="git push origin HEAD"
alias gpt="git push origin HEAD && git push --tags"
alias wip="git commit -m'WIP' . && git push origin HEAD"
alias grok="ngrok start rem.jsbin-dev.com static.rem.jsbin-dev.com learn.rem.jsbin-dev.com"
alias gl='git log'
alias glp5='git log -5 --pretty --oneline' # view your last 5 latest commits each on their own line
alias glt='git log --all --graph --decorate --oneline --simplify-by-decoration' # pretty branch status
alias glsw='git log -S' # search the commit history for the word puppy and display matching commits (glsw [word])
alias gs='git status'
alias gd='git diff'
alias gm='git commit -m'
alias gam='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gbt=git_list_branches
alias gpu='git pull origin HEAD --prune'
alias gcl='git clone'
alias gta='git tag -a -m'
alias gf='git reflog' # allows you to see every step you have made with git allowing you to retract and reinstate your steps
alias gap='git add -p' # step through each change, or hunk
alias gsl='git shortlog -sn' # quickly get a list of contributors and see how many commits each person has
alias gws='git diff --shortstat "@{0 day ago}"' # how many lines of code you have written today
alias gwts='git ls-files | xargs wc -l' # count number of lines of code in a git project
alias ggmp='git checkout -' # jump back to to your last branch
alias gst='git stash' # stash git changes and put them into your list
alias gdtp='git stash pop' # bring back your changes, but it removes them from your stash
alias gchp='git cherry-pick' # cherry pick the committed code in your own branch (gchp [hash])
alias gcln='git clean -xfd' # remove untracked files

# Undo a `git push`
alias undopush="git push -f origin HEAD^:master"

# `cd` to Git repo root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'

# Gist
alias gist-paste="gist --private --copy --paste --filename"  # gist-paste filename.ext -- create private Gist from the clipboard contents
alias gist-file="gist --private --copy"  # gist-file filename.ext -- create private Gist from a file
