#!/bin/bash

# Ensure that the D-Bus Communication System is running properly to fix
# File management, authentication, and other essential system processes

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi


## Ensure that GTK themes are applied uniformly in the Desktop Environment
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" 


## Start apps on X

# system apps
bash /home/codin/.screenlayout/screen_layout.sh &
#bash /home/codin/scripts/live_wallpaper &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pasystray &
udiskie &
syndaemon -i 1 -K -R &
dunst -config ~/.config/dunst/dunstrc &
blueman-applet &
nm-applet &

# my apps
#slack &
#skypeforlinux &
redshift-gtk &
xfce4-clipman &
#unclutter -root -visible &
#gnome-keyring-daemon -r -d
#hexchat
#transmission-gtk
#opera
#obs
#ptxconf
#thunar
#spotify
#virt-manager
#filezilla
#nautilus
#ptxconf
xbacklight -set 65
feh --bg-fill ~/Pictures &
